module.exports = [
  {
    "id": 1,
    "student_id": 2,
    "name": "Mai_CV",
    "avatar": "",
    "position": "intern ruby",
    "dateofbirth": "1993-09-09",
    "gender": "Female",
    "phone": "1692630370",
    "email": "ltmai93@gmail.com",
    "address": "Van Chuong, Dong Da, Ha Noi",
    "link": "",
    "intent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    "skill": "",
    "hobby": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    "year_start": "0000-00-00",
    "year_stop": "0000-00-00",
    "grade": 4,
    "school": "Đại học bách khoa hà nội",
    "major": "Công nghệ thông tin",
    "cpa": "3.08",
    "majorskill": "java",
    "otherskill": "c",
    "majorskill_level": 92,
    "otherskill_level": 34,
    "created_at": "2017-03-22 00:00:00",
    "updated_at": "2017-03-22 00:00:00",
    "more_information": "",
    "destination": ""
  },
  {
    "id": 2,
    "student_id": 1,
    "name": "PhuongCV",
    "avatar": "",
    "position": "intern ruby",
    "dateofbirth": "1995-02-01",
    "gender": "Male",
    "phone": "965868102",
    "email": "phuong@gmail.com",
    "address": "HaNoi",
    "link": "",
    "intent": "",
    "skill": "",
    "hobby": "",
    "year_start": "0000-00-00",
    "year_stop": "0000-00-00",
    "grade": 4,
    "school": "Đại học bách khoa hà nội",
    "major": "Công nghệ thông tin",
    "cpa": "2.57",
    "majorskill": "java",
    "otherskill": "c",
    "majorskill_level": 10,
    "otherskill_level": 95,
    "created_at": "2017-03-22 00:00:00",
    "updated_at": "2017-03-22 00:00:00",
    "more_information": "",
    "destination": ""
  },
  {
    "id": 3,
    "student_id": 3,
    "name": "Huong-CV",
    "avatar": "",
    "position": "intern php",
    "dateofbirth": "1993-09-09",
    "gender": "Female",
    "phone": "99283742743",
    "email": "huong@gmail.com",
    "address": "Lang Son",
    "link": "",
    "intent": "",
    "skill": "",
    "hobby": "Listening to Music, playing game",
    "year_start": "0000-00-00",
    "year_stop": "0000-00-00",
    "grade": 4,
    "school": "Đại học bách khoa hà nội",
    "major": "Công nghệ thông tin",
    "cpa": "3.00",
    "majorskill": "java",
    "otherskill": "c",
    "majorskill_level": 50,
    "otherskill_level": 12,
    "created_at": "2017-03-22 00:00:00",
    "updated_at": "2017-03-22 00:00:00",
    "more_information": "",
    "destination": ""
  },
  {
    "id": 4,
    "student_id": 4,
    "name": "Lan-CV",
    "avatar": "",
    "position": "intern Android",
    "dateofbirth": "1993-09-09",
    "gender": "Female",
    "phone": "89237287874",
    "email": "lan@gmail.com",
    "address": "Nam Dinh",
    "link": "",
    "intent": "",
    "skill": "",
    "hobby": "",
    "year_start": "0000-00-00",
    "year_stop": "0000-00-00",
    "grade": 4,
    "school": "Đại học bách khoa hà nội",
    "major": "Công nghệ thông tin",
    "cpa": "3.57",
    "majorskill": "java",
    "otherskill": "c",
    "majorskill_level": 23,
    "otherskill_level": 43,
    "created_at": "2017-03-22 00:00:00",
    "updated_at": "2017-03-22 00:00:00",
    "more_information": "",
    "destination": ""
  }
]
