module.exports =  [
    {
      "id": 1,
      "name": "Tran Huu Nam Phuong",
      "class": "LTU12A",
      "CSTT": 9,
      "timechecking": 9,
      "report": 9,
      "demo": 9,
      "material": 9,
      "GPA": 9,
      "Result": "A",
    },
    {
      "id": 2,
      "name": "Le Thi Mai",
      "class": "LTU12A",
      "CSTT": 9,
      "timechecking": 10,
      "report": 9,
      "demo": 9,
      "material": 9,
      "GPA": 9,
      "Result": "A",
    },
    {
      "id": 3,
      "name": "Le Thi Huong",
      "class": "LTU12A",
      "CSTT": 9,
      "timechecking": 9,
      "report": 9,
      "demo": 9,
      "material": 9,
      "GPA": 9,
      "Result": "A",
    },
    {
        "id": 4,
        "name": "Le Thi Lan",
        "class": "INPG12A",
        "CSTT": 8,
        "timechecking": 8,
        "report": 8,
        "demo": 8,
        "material": 8,
        "GPA": 8,
        "Result": "B",
    },
    {
        "id": 5,
        "name": "Nguyen Thi Hoa",
        "class": "VUWIT12",
        "CSTT": 9,
        "timechecking": 9,
        "report": 9,
        "demo": 9,
        "material": 9,
        "GPA": 9,
        "Result": "A",
    },
    {
        "id": 6,
        "name": "Le Van Duc",
        "class": "VUWIT12",
        "CSTT": 9,
        "timechecking": 9,
        "report": 9,
        "demo": 9,
        "material": 9,
        "GPA": 9,
        "Result": "A",
    },
    {
        "id": 7,
        "name": "Le Nam Phuong",
        "class": "VUWIT12",
        "CSTT": 9,
        "timechecking": 9,
        "report": 9,
        "demo": 9,
        "material": 9,
        "GPA": 9,
        "Result": "A",
    },
    {
        "id": 11,
        "name": "Le Thi Loan",
        "class": "LTU11B",
        "CSTT": 9,
        "timechecking": 9,
        "report": 9,
        "demo": 9,
        "material": 9,
        "GPA": 9,
        "Result": "A",
    },
    {
        "id": 19,
        "name": "Nguyen Nhat Le",
        "class": "LTU13A",
        "CSTT": 6,
        "timechecking": 6,
        "report": 6,
        "demo": 6,
        "material": 6,
        "GPA": 6,
        "Result": "C",
    },
    {
        "id": 23,
        "name": "Nguyen Tuong Minh",
        "class": "LTU12B",
        "CSTT": 9,
        "timechecking": 9,
        "report": 10,
        "demo": 10,
        "material": 10,
        "GPA": 10,
        "Result": "A",
    },
    {
        "id": 24,
        "name": "Le Thi Tinh",
        "class": "LTU12A",
        "CSTT": 9,
        "timechecking": 9,
        "report": 9,
        "demo": 9,
        "material": 9,
        "GPA": 9,
        "Result": "A",
    }

  ]
