module.exports = [
    {
        "id": 1,
        "student_id": "1",
        "name": "Tran Huu Nam Phuong",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "30%",
        "comment": "Good",
    },
    {
        "id": 2,
        "student_id": "2",
        "name": "Le Thi Mai",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "95%",
        "comment": "Sai chu de",
    },
    {
        "id": 3,
        "student_id": "23",
        "name": "huong",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "100%",
        "comment": "good",
    },
    {
        "id": 4,
        "student_id": "24",
        "name": "lan",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "unmeasured",
        "comment": "Good",
    },
    {
        "id": 5,
        "student_id": "25",
        "name": "hoa",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "90%",
        "comment": "ok",
    },
    {
        "id": 6,
        "student_id": "26",
        "name": "duc",
        "midterm": "google.com",
        "final": "google.com",
        "timechecking": "80%",
        "comment": "Good",
    },
]
