module.exports =
    [
        {
            "id": 1,
            "mssv": 20138965,
            "class": "LTU12A",
            "username": "namphuong",
            "email": "phuong@gmail.com",
            "name": "nam phương",
            "phonenumber": 965868102,
            "dateofbirth": "0000-00-00",
            "gender": 1,
            "lock": 0,
            "status": 1,
        },
        {
            "id": 2,
            "mssv": 20147892,
            "class": "LTU14",
            "username": "mai",
            "email": "mai@gmail.com",
            "name": "phuongzzz",
            "phonenumber": 1234567890,
            "dateofbirth": "0000-00-00",
            "gender": 1,
            "lock": 0,
            "status": 1,
        },
        {
            "id": 3,
            "mssv": 20118992,
            "class": "LTU11A",
            "username": "huong",
            "email": "20118994@gmail.com",
            "name": "Le Thi Huong",
            "phonenumber": 123456789,
            "dateofbirth": "0000-00-00",
            "gender": 0,
            "lock": 0,
            "status": 1,
        },
        {
            "id": 4,
            "mssv": 20132903,
            "class": "VUWIT12B",
            "username": "lan",
            "email": "lan@gmail.com",
            "name": "Le Thi Lan",
            "phonenumber": 123456789,
            "dateofbirth": "0000-00-00",
            "gender": 0,
            "lock": 0,
            "status": 1,
        },
        {
            "id": 5,
            "mssv": 20132903,
            "class": "VUWIT12B",
            "username": "hoa",
            "email": "hoa@gmail.com",
            "name": "Nguyen Thi Hoa",
            "phonenumber": 123456789,
            "dateofbirth": "0000-00-00",
            "gender": 0,
            "lock": 0,
            "status": 1,
        },
        {
            "id": 6,
            "mssv": 20132903,
            "class": "VUWIT12B",
            "username": "duc",
            "email": "duc@gmail.com",
            "name": "Le Van Duc",
            "phonenumber": 123456789,
            "dateofbirth": "0000-00-00",
            "gender": 0,
            "lock": 0,
            "status": 1,
        },

    ]
