module.exports =
  [
    {
      "name": "Trần Lê Hải",
      "topic_id": 2,
      "title": "Ruby on Rails",
      "categories": "Web Dev",
      "description": "Building application with Rails",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Tran Quang Chien",
      "topic_id": 3,
      "title": "Java",
      "categories": "Desktop App",
      "description": "Building weather forecast using Java",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Nguyen Van Quy",
      "topic_id": 4,
      "title": "PHP",
      "categories": "PHP",
      "description": "Building website with PHP",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Nguyen Phuong Thao",
      "topic_id": 5,
      "title": "Perl",
      "categories": "Desktop App",
      "description": "Building weather forecast using Perl",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Hoang Ngoc Luc",
      "topic_id": 6,
      "title": "Rust",
      "categories": "System programing",
      "description": "Program simple system with Rust",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Ninh Manh Dung ",
      "topic_id": 7,
      "title": "Python",
      "categories": "Machine Learning",
      "description": "Building face detection system",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Le Van Duc",
      "topic_id": 8,
      "title": "Ruby",
      "categories": "Metasploit",
      "description": "Learning security",
      "no_interns": "5",
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    }
  ]
