module.exports =
  [
    {
      "name": "Trần Lê Hải",
      "topic_id": 2,
      "title": "Ruby on Rails",
      "categories": "Web Dev",
      "description": "Building application with Rails",
      "max": 5,
      "no_intern": 2,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Tran Quang Chien",
      "topic_id": 3,
      "title": "Java",
      "categories": "Desktop App",
      "description": "Building weather forecast using Java",
      "max": 5,
      "no_intern":2,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Nguyen Van Quy",
      "topic_id": 4,
      "title": "PHP",
      "categories": "PHP",
      "description": "Building website with PHP",
      "max": 5,
      "no_intern": 2,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Nguyen Phuong Thao",
      "topic_id": 5,
      "title": "Perl",
      "categories": "Desktop App",
      "description": "Building weather forecast using Perl",
      "max": 5,
      "no_intern": 2,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Hoang Ngoc Luc",
      "topic_id": 6,
      "title": "Rust",
      "categories": "System programing",
      "description": "Program simple system with Rust",
      "max": 8,
      "no_intern": 5,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Ninh Manh Dung ",
      "topic_id": 7,
      "title": "Python",
      "categories": "Machine Learning",
      "description": "Building face detection system",
      "max": 7,
      "no_intern": 3,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Le Van Duc",
      "topic_id": 8,
      "title": "Ruby",
      "categories": "Metasploit",
      "description": "Learning security",
      "max": 5,
      "no_intern": 4,
      "content": "",
      "timelimit": "3months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-04-03",
      "link_topic": "",
      "company_name": "VIETTEL"
    },
    {
      "name": "Pham Hoang Hai",
      "topic_id": 9,
      "title": "Python",
      "categories": "Application Development",
      "description": "Building Naive-Bayes application to detect website attack",
      "max": 3,
      "no_intern": 3,
      "content": "",
      "timelimit": "4 months",
      "status": "0",
      "start": "2017-06-01",
      "stop": "2017-11-01",
      "link_topic": "",
      "company_name": "VNIST"
    },
    {
      "name": "Hoang Thu Trang",
      "topic_id": 10,
      "title": "Java",
      "categories": "Application Development",
      "description": "Building tool to manage student topic in SIE",
      "max": 6,
      "no_intern": 4,
      "content": "",
      "timelimit": "5 months",
      "status": "0",
      "start": "2017-01-02",
      "stop": "2017-07-02",
      "link_topic": "",
      "company_name": "FPT"
    },
    {
      "name": "Dang Bich Ngoc",
      "topic_id": 11,
      "title": "React",
      "categories": "Webiste Development",
      "description": "Building a website to manage internship student in SIE",
      "max": 5,
      "no_intern": 2,
      "content": "",
      "timelimit": "4 months",
      "status": "0",
      "start": "2017-01-03",
      "stop": "2017-06-03",
      "link_topic": "",
      "company_name": "CMC"
    },
    {
      "name": "Phan Manh Thuong",
      "topic_id": 12,
      "title": "Java",
      "categories": "Application Development",
      "description": "Building application to create question for student in gift format",
      "max": 4,
      "no_intern": 3,
      "content": "",
      "timelimit": "3 months",
      "status": "0",
      "start": "2017-06-01",
      "stop": "2017-11-01",
      "link_topic": "",
      "company_name": "FPT"
    },
    {
      "name": "Tran Van Lang",
      "topic_id": 13,
      "title": "Android",
      "categories": "Application Development",
      "description": "Building mobile application to searching information for each location",
      "max": 6,
      "no_intern": 3,
      "content": "",
      "timelimit": "7 months",
      "status": "0",
      "start": "2017-05-01",
      "stop": "2017-12-01",
      "link_topic": "",
      "company_name": "Framgia"
    },
    {
      "name": "Vo Hong Bao Chau",
      "topic_id": 14,
      "title": "Ruby on Rails",
      "categories": "Website Development",
      "description": "Building a website to advertise Media information throw internet",
      "max": 6,
      "no_intern": 2,
      "content": "",
      "timelimit": "5 months",
      "status": "0",
      "start": "2017-11-01",
      "stop": "2017-06-01",
      "link_topic": "",
      "company_name": "Framgia"
    },
    {
      "name": "Nguyen Hoang Liem",
      "topic_id": 15,
      "title": "Java",
      "categories": "Application Development",
      "description": "Building tool to filter spam mail in Google",
      "max": 7,
      "no_intern": 2,
      "content": "",
      "timelimit": "3 months",
      "status": "0",
      "start": "2017-12-01",
      "stop": "2017-08-01",
      "link_topic": "",
      "company_name": "VNIST"
    },
    {
      "name": "Huynh Cao Tuan",
      "topic_id": 16,
      "title": "Ruby on Rails",
      "categories": "Website Development",
      "description": "Building a website to advertise Media information throw internet",
      "max": 6,
      "no_intern": 2,
      "content": "",
      "timelimit": "5 months",
      "status": "0",
      "start": "2017-11-01",
      "stop": "2017-06-01",
      "link_topic": "",
      "company_name": "Framgia"
    }
  ]
