module.exports =
  [
    {
      "id": 82,
      "username": "admin",
      "email": "ltu@gmail.com",
      "name": "ltu",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "groupname": "admin"
    },
    {
      "id": 142,
      "username": "namphuong",
      "email": "phuong@gmail.com",
      "name": "nam phương",
      "phonenumber": 965868102,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "groupname": "admin"
    },
    {
      "id": 152,
      "username": "phuongzzz",
      "email": "phuongphuong@gmail.com",
      "name": "phuongzzz",
      "phonenumber": 1234567890,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "groupname": "admin"
    },
    {
      "id": 112,
      "username": "banhmai",
      "email": "btqm@gmail.com",
      "name": "Bành Thị Quỳnh Mai",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "teacher_instructions"
    },
    {
      "id": 102,
      "username": "huonggiang",
      "email": "vthg@gmail.com",
      "name": "Vũ Thị Hương GIang",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "teacher_managers"
    },
    {
      "id": 122,
      "username": "leha",
      "email": "halt@gmail.com",
      "name": "Trần Lê Hải",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "groupname": "company's agents"
    },
    {
      "id": 132,
      "username": "phuongthao",
      "email": "thaopt@gmail.com",
      "name": "Phạm Thị Thảo",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "company's instructors"
    },
    {
      "id": 92,
      "username": "lemai",
      "email": "20118994@gmail.com",
      "name": "Lê Thị Mai",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "students"
    },
    {
      "id": 2,
      "username": "lelan",
      "email": "lan@gmail.com",
      "name": "Le Thi Lan",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "students"
    },
    {
      "id": 3,
      "username": "trungkien",
      "email": "kientt@soict.hust.edu.vn",
      "name": "Tran Trung Kien",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "teacher_managers"
    },
    {
      "id": 4,
      "username": "binhminh",
      "email": "minhbn@soict.hust.edu.vn",
      "name": "Nguyen Binh Minh",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "teacher_instructions"
    },
    {
      "id": 6,
      "username": "nguyentruong",
      "email": "truong@vnist.com",
      "name": "Nguyen Van Truong",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "groupname": "company's instructors"
    }
  ]
