module.exports =
  [
    {
      "id": 82,
      "username": "admin",
      "email": "ltu@gmail.com",
      "name": "ltu",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "role": "admin"
    },
    {
      "id": 1,
      "username": "namphuong",
      "email": "phuong@gmail.com",
      "name": "nam phương",
      "phonenumber": 965868102,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 7,
      "username": "phuongzzz",
      "email": "phuongphuong@gmail.com",
      "name": "phuongzzz",
      "phonenumber": 1234567890,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "role": "student"
    },
    {
      "id": 112,
      "username": "banhmai",
      "email": "btqm@gmail.com",
      "name": "Bành Thị Quỳnh Mai",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "teacher_instructions"
    },
    {
      "id": 102,
      "username": "huonggiang",
      "email": "vthg@gmail.com",
      "name": "Vũ Thị Hương GIang",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "teacher_managers"
    },
    {
      "id": 122,
      "username": "leha",
      "email": "halt@gmail.com",
      "name": "Trần Lê Hải",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 1,
      "lock": 0,
      "status": 1,
      "role": "company's agents"
    },
    {
      "id": 132,
      "username": "phuongthao",
      "email": "thaopt@gmail.com",
      "name": "Phạm Thị Thảo",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "company's instructors"
    },
    {
      "id": 2,
      "username": "mai",
      "email": "20118994@gmail.com",
      "name": "Lê Thị Mai",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 4,
      "username": "lan",
      "email": "lan@gmail.com",
      "name": "Le Thi Lan",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 9,
      "username": "trungkien",
      "email": "kientt@soict.hust.edu.vn",
      "name": "Tran Trung Kien",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "teacher_managers"
    },
    {
      "id": 8,
      "username": "binhminh",
      "email": "minhbn@soict.hust.edu.vn",
      "name": "Nguyen Binh Minh",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "teacher_instructions"
    },
    {
      "id": 10,
      "username": "nguyentruong",
      "email": "truong@vnist.com",
      "name": "Nguyen Van Truong",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "company's instructors"

    },
    {
      "id": 17,
      "username": "hanhphuc",
      "email": "hanhpn@soict.hust.edu.vn",
      "name": "Nguyen Hanh Phuc",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "teacher_instructions"
    },
    {
      "id": 6,
      "username": "duc",
      "email": "duc@gmail.com",
      "name": "Le Van Duc",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 3,
      "username": "huong",
      "email": "20118994@gmail.com",
      "name": "Le Thi Huong",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 5,
      "username": "hoa",
      "email": "hoa@gmail.com",
      "name": "Nguyen Thi Hoa",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 11,
      "username": "loan",
      "email": "loan@gmail.com",
      "name": "Le Thi Loan",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 19,
      "username": "le",
      "email": "le@gmail.com",
      "name": "Nguyen Nhat Le",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 23,
      "username": "minh",
      "email": "tuongminh@gmail.com",
      "name": "Nguyen Tuong Minh",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
    {
      "id": 240,
      "username": "tinh",
      "email": "tinh@gmail.com",
      "name": "Le Thi Tinh",
      "phonenumber": 123456789,
      "dateofbirth": "0000-00-00",
      "gender": 0,
      "lock": 0,
      "status": 1,
      "role": "students"
    },
  ]
